moduledir '../external_modules'

mod 'puppetlabs/stdlib',  '4.9.0'
mod 'puppetlabs/apt',     '2.2.0'
mod 'vshn/gitlab',        '1.5.0'
mod 'puppetlabs/java',    '1.4.2'
mod 'darin/zypprepo',     '1.0.2'
mod 'nanliu/staging',     '1.0.3'
mod 'camptocamp/archive', '0.8.1'
mod 'rtyler/jenkins',     '1.6.1'

mod 'artifactory',
  :git => 'https://github.com/spanneberg/puppet-artifactory.git'
